// #define WITH_EXPLICIT_DISSIPATION


// #define INCOMPRESSIBLE
// #define DEALIASING

#define HEAT_EQ
#define WITH_EXPLICIT_DISSIPATION
// #define BOUSSINESQ
// #define STRATIFICATION
// #define STRAT_DIR    2
