

#define INCOMPRESSIBLE
#define WITH_EXPLICIT_DISSIPATION
#define DEALIASING
#define MHD
#define ANISOTROPIC_DIFFUSION

#define DEBUG
#define DDEBUG

#define BOUSSINESQ
#define STRATIFICATION
#define STRAT_DIR    2
#define SUPERTIMESTEPPING
#define RKL
